sudo: required
services:
    - docker 

before_install:
    - docker build -t beauilieudev/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true beauilieudev/docker-react npm run test -- --coverage
   
   
   
   
   
   
   
   
   
        # language: generic 
    